# Generated by Django 2.0.6 on 2019-12-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MRS', 'Madame'), ('MR', 'Monsieur')], max_length=3)),
                ('name', models.CharField(max_length=12, verbose_name='Nom')),
                ('surname', models.CharField(max_length=12, verbose_name='Prénom')),
                ('enterprise_name', models.CharField(max_length=12, verbose_name='Société')),
                ('phone_number', models.CharField(max_length=20, verbose_name='numéro téléphone')),
                ('demandes_particulieres', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='demandes particulières')),
            ],
            options={
                'verbose_name': 'Contact société',
                'verbose_name_plural': 'Contacts sociétés',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('inscription_date', models.DateTimeField(verbose_name='date of inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Teatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('url_site', models.URLField(default='www.urlvide.fr')),
                ('disciplines', models.ManyToManyField(to='inscription_pedago.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Validation_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Student')),
                ('teatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Teatcher')),
            ],
        ),
    ]
