# Generated by Django 2.2.7 on 2019-12-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MRS', 'Madame'), ('MR', 'Monsieur')], max_length=3, verbose_name='Civilité')),
                ('name', models.CharField(max_length=12, verbose_name='Nom')),
                ('surname', models.CharField(max_length=12, verbose_name='Prénom')),
                ('enterprise_name', models.CharField(max_length=12, verbose_name='Société')),
                ('phone_number', models.CharField(max_length=20, verbose_name='numéro téléphone')),
                ('demandes_particulieres', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='demandes particulières')),
            ],
            options={
                'verbose_name': 'Contact société',
                'verbose_name_plural': 'Contacts sociétés',
            },
        ),
    ]
