# Generated by Django 2.2.6 on 2019-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teatcher',
            name='disciplines',
            field=models.ManyToManyField(to='inscription_pedago.Discipline'),
        ),
    ]
