# Generated by Django 2.2.6 on 2019-10-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teatcher',
            name='surname',
            field=models.CharField(default='default_surname', max_length=200),
        ),
        migrations.AddField(
            model_name='teatcher',
            name='url_site',
            field=models.URLField(default='url_vide'),
        ),
        migrations.CreateModel(
            name='Validation_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Student')),
                ('teatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Teatcher')),
            ],
        ),
        migrations.AddField(
            model_name='teatcher',
            name='disciplines',
            field=models.ManyToManyField(to='inscription_pedago.Discipline'),
        ),
    ]
