# Generated by Django 2.2.6 on 2019-10-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teatcher',
            old_name='name',
            new_name='teatcher_name',
        ),
    ]
