# Generated by Django 2.2.6 on 2019-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0002_auto_20191030_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='teatcher',
            name='surname',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teatcher',
            name='url_site',
            field=models.CharField(default='url_vide', max_length=200),
        ),
    ]
