# Generated by Django 2.2.6 on 2019-10-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0002_auto_20191031_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatcher',
            name='url_site',
            field=models.URLField(default='urlvide.fr'),
        ),
    ]
