# Generated by Django 2.2.6 on 2019-10-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0003_auto_20191030_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatcher',
            name='url_site',
            field=models.URLField(default='url_vide'),
        ),
        migrations.CreateModel(
            name='Validation_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('teatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Teatcher')),
            ],
        ),
    ]
