# Generated by Django 2.2.7 on 2019-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0003_auto_20191031_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatcher',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teatcher',
            name='url_site',
            field=models.URLField(default='www.urlvide.fr'),
        ),
    ]
