# Generated by Django 2.2.7 on 2019-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0004_auto_20191128_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('demandes_particulieres', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
