# Generated by Django 2.2.6 on 2019-10-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0004_auto_20191030_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation_code',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription_pedago.Student'),
        ),
    ]
