# Generated by Django 2.0.6 on 2019-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0005_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='demandes_particulieres',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
