# Generated by Django 2.0.6 on 2019-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedago', '0007_auto_20191210_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact société', 'verbose_name_plural': 'Contacts sociétés'},
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='demandes_particulieres',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='demandes particulières'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Nom société'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='numéro téléphone'),
        ),
    ]
